### ISSUE TITLE
Number on review badge

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/wsi-superpixel-guided-labeling#149]
It isn't initially obvious that the badge on the Review button indicates number of reviewed superpixels.  We should add a tooltip to that effect.

Also, maybe it is just me, but I feel that having a badge number implies that there should be something I can do to make it go away -- that is, if I caught up on reviews, it would be zero.  Would it make more sense to have this be the number of unreviewed superpixels (maybe that were labelled by someone else)?

**Comment by bnmajor** [comment]
This badge count is there largely because it was there on the mock-ups. Personally I agree that it is confusing and I'm not even sure how useful it actually is... There was no specific request for this so my actual preference would be to drop it altogether. If we don't want to do that then I agree that at minimum a tooltip would be useful and that counting the remaining superpixels to review makes more sense than counting completed reviews.
