### ISSUE TITLE
Improve pixelmap interaction

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/wsi-superpixel-guided-labeling#44]
### Available interactions

1. Category selection
2. Category creation
3. Click a superpixel to set/unset category

### Desired interactions

1. Click + drag to paint

### Available interactions
None

### Potential interactions

1. Category selection
2. Category creation
3. Click a superpixel to set/unset category
4. Click + drag to paint

## Next steps

1. Implement click + drag for initial label UI
2. Determine what interactions are needed for the main guided labeling UI

**Comment by jeffbaumes** [comment]
* Add chip review, by manual label as highest priority. Ideally sort/group by who made annotation, what slide, what class, where do machine and label disagree. By manual label then by slide would be a good default
* For a given chip, want to be able to show context ("minimize" the mosaic view to show the main viewer? Or perhaps we need it to be more lightweight without leaving the mosaic context).
* 9-25 at a time would be good, should be able to easily scroll or page (@cooperlab had a preference for scrolling rather than paging)
* Keep chip location stable even if relabelled, maybe show new label more boldly to indicate a change

We also discussed paper trail, be able to compare two reviewers, etc. which is out of scope for now but we should try to be forward-thinking about how we'd support that.

**Comment by cooperlab** [comment]
I don't have anything to add to this.

**Comment by bnmajor** [comment]
I believe all of these features were already added for the initial labeling step and the remaining features for the guided labeling step have been added in #120.

@jeffbaumes @manthey Let me know if you disagree

**Comment by bnmajor** [comment]
Closing as I believe this is completed now. We can open new issues if there are additional features missing.
